
INSERT INTO USUARIO (ID,NOME,LOGIN,SENHA) VALUES (1,'Luiz Gabriel','login','j1+Fsg/B7OH/5W1+lbAGLg==');
INSERT INTO EC (ID,NOME,ENDERECO,NUMERO,CIDADE,PAIS,POS,COD_USUARIO) VALUES (1,'Padaria do Joao','Avenida da Padaria',12121, 'Paulinia','Brasil','54512154',1);

INSERT INTO PAIS (ID, NOME) VALUES (1, 'Argentina');
INSERT INTO PAIS (ID, NOME) VALUES (2, 'Alemanha');
INSERT INTO PAIS (ID, NOME) VALUES (3, 'Brasil');
INSERT INTO PAIS (ID, NOME) VALUES (4, 'Canadá');
INSERT INTO PAIS (ID, NOME) VALUES (5, 'Estados Unidos');
INSERT INTO PAIS (ID, NOME) VALUES (6, 'Zimbabue');
